config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :tweets

  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user



 

    def self.calc_flop_action_distribution(posts)
        all_actions = posts.pluck(:action1, :action2, :action3, :action4, :action5, :action6, :action7, :action8, :action9, :action10).flatten.compact

        check_count = all_actions.count("チェック")
        bet_count   = all_actions.count("ベット")
        call_count  = all_actions.count("コール")
        raise_count = all_actions.count("レイズ")
        fold_count = all_actions.count("フォールド")

        total = (check_count + bet_count + call_count + raise_count + fold_count).to_f

        check_percent = total.zero? ? 0.0 : (check_count / total * 100).round(1)
        bet_percent   = total.zero? ? 0.0 : (bet_count / total * 100).round(1)
        call_percent  = total.zero? ? 0.0 : (call_count / total * 100).round(1)
        raise_percent = total.zero? ? 0.0 : (raise_count / total * 100).round(1)
        fold_percent = total.zero? ? 0.0 : (fold_count / total * 100).round(1)

        [check_percent, bet_percent, call_percent, raise_percent, fold_percent]
    end
 def self.calc_flop_action_distribution1(posts)
        preflop_actions = posts.pluck(:action1, :action2, :action3).flatten.compact

         check_count1 = preflop_actions.count("チェック")
         bet_count1   = preflop_actions.count("ベット")
         call_count1  = preflop_actions.count("コール")
         raise_count1 = preflop_actions.count("レイズ")
         fold_count1 = preflop_actions.count("フォールド")

        total = ( check_count1 +  bet_count1 +  call_count1 +  raise_count1 + fold_count1).to_f

         check_percent1 = total.zero? ? 0.0 : (check_count1 / total * 100).round(1)
        bet_percent1   = total.zero? ? 0.0 : (bet_count1 / total * 100).round(1)
        call_percent1  = total.zero? ? 0.0 : (call_count1 / total * 100).round(1)
        raise_percent1 = total.zero? ? 0.0 : (raise_count1 / total * 100).round(1)
        fold_percent1 = total.zero? ? 0.0 : (fold_count1 / total * 100).round(1)


        [check_percent1, bet_percent1, call_percent1, raise_percent1, fold_percent1]
    end
    def self.calc_flop_action_distribution2(posts)
        frop_actions = posts.pluck(:action4, :action5).flatten.compact

        check_count2 = frop_actions.count("チェック")
        bet_count2   = frop_actions.count("ベット")
        call_count2  = frop_actions.count("コール")
        raise_count2 = frop_actions.count("レイズ")
        fold_count2 = frop_actions.count("フォールド")

        total = (check_count2 + bet_count2 + call_count2 + raise_count2 + fold_count2).to_f

        check_percent2 = total.zero? ? 0.0 : (check_count2 / total * 100).round(1)
        bet_percent2   = total.zero? ? 0.0 : (bet_count2 / total * 100).round(1)
        call_percent2  = total.zero? ? 0.0 : (call_count2 / total * 100).round(1)
        raise_percent2 = total.zero? ? 0.0 : (raise_count2 / total * 100).round(1)
        fold_percent2 = total.zero? ? 0.0 : (fold_count2 / total * 100).round(1)


        [check_percent2, bet_percent2, call_percent2, raise_percent2, fold_percent2]
    end
    def self.calc_flop_action_distribution3(posts)
        turn_actions = posts.pluck(:action6, :action7).flatten.compact

        check_count3 = turn_actions.count("チェック")
        bet_count3   = turn_actions.count("ベット")
        call_count3  = turn_actions.count("コール")
        raise_count3 = turn_actions.count("レイズ")
        fold_count3 = turn_actions.count("フォールド")
      

        total = (check_count3 + bet_count3 + call_count3 + raise_count3 + fold_count3).to_f

        check_percent3 = total.zero? ? 0.0 : (check_count3 / total * 100).round(1)
        bet_percent3   = total.zero? ? 0.0 : (bet_count3 / total * 100).round(1)
        call_percent3  = total.zero? ? 0.0 : (call_count3 / total * 100).round(1)
        raise_percent3 = total.zero? ? 0.0 : (raise_count3 / total * 100).round(1)
        fold_percent3 = total.zero? ? 0.0 : (fold_count3 / total * 100).round(1)


        [check_percent3, bet_percent3, call_percent3, raise_percent3, fold_percent3]
    end
    def self.calc_flop_action_distribution4(posts)
        river_actions = posts.pluck(:action8, :action9, :action10).flatten.compact

        check_count4 = river_actions.count("チェック")
        bet_count4   = river_actions.count("ベット")
        call_count4  = river_actions.count("コール")
        raise_count4 = river_actions.count("レイズ")
        fold_count4 = river_actions.count("フォールド")

        total = (check_count4 + bet_count4 + call_count4 + raise_count4 + fold_count4).to_f

        check_percent4 = total.zero? ? 0.0 : (check_count4 / total * 100).round(1)
        bet_percent4   = total.zero? ? 0.0 : (bet_count4 / total * 100).round(1)
        call_percent4  = total.zero? ? 0.0 : (call_count4 / total * 100).round(1)
        raise_percent4 = total.zero? ? 0.0 : (raise_count4 / total * 100).round(1)
        fold_percent4 = total.zero? ? 0.0 : (fold_count4 / total * 100).round(1)


        [check_percent4, bet_percent4, call_percent4, raise_percent4, fold_percent4]
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
   before_action :authenticate_user!
  def index
    @tweets = current_user.tweets
    tweet_ids = []
    action1_chart = @tweets
    action2_chart = @tweets
    action3_chart = @tweets
    action4_chart = @tweets
    action5_chart = @tweets
    action6_chart = @tweets
    action7_chart = @tweets
    action8_chart = @tweets
    action9_chart = @tweets
    action10_chart = @tweets
    flop_action_chart = @tweets
    flop_action_chart1 = @tweets
    flop_action_chart2 = @tweets
    flop_action_chart3 = @tweets
    flop_action_chart4 = @tweets
    @check_percent, @bet_percent, @call_percent, @raise_percent, @fold_percent = Tweet.calc_flop_action_distribution(flop_action_chart)
    @check_percent1, @bet_percent1, @call_percent1, @raise_percent1, @fold_percent1 = Tweet.calc_flop_action_distribution1(flop_action_chart1)
    @check_percent2, @bet_percent2, @call_percent2, @raise_percent2, @fold_percent2 = Tweet.calc_flop_action_distribution2(flop_action_chart2)
    @check_percent3, @bet_percent3, @call_percent3, @raise_percent3, @fold_percent3 = Tweet.calc_flop_action_distribution3(flop_action_chart3)
    @check_percent4, @bet_percent4, @call_percent4, @raise_percent4, @fold_percent4= Tweet.calc_flop_action_distribution4(flop_action_chart4)
  

   if params[:search].present?
  keyword = "%#{params[:search]}%"
  search_columns = ["shurui", "body","shurui", "rate", "ninnzuu","position", "myhand", "suit","mark", "frop1", "frop2","frop3", "turn", "river","turn1", "turn2", "turn3","action1", "turn4", "action2","action3", "action4", "action5","action6", "action7", "action8","action9", "action10"]
  query = search_columns.map { |c| "#{c} LIKE :keyword" }.join(" OR ")
  @tweets = @tweets.where(query, keyword: keyword)
   end
  end


  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end

  end

  def show
    @tweet = Tweet.find(params[:id])
  end

 def top
 end

def edit
    @tweet = Tweet.find(params[:id])
end

def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "index", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body,:shurui, :rate, :ninnzuu,:position, :myhand, :suit,:mark, :frop1, :frop2,:frop3, :turn, :river,:turn1, :turn2, :turn3,:action1, :turn4, :action2,:action3, :action4, :action5,:action6, :action7, :action8,:action9, :action10, :frop1m, :frop2m, :frop3m, :turnm, :riverm,)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  


  <div class="field">
    <%= f.label :ゲームの種類 %>
    <%= f.select :shurui, 
    [["リングゲーム", "リングゲーム"],
     ["トーナメント", "トーナメント"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :レート %>
    <%= f.text_field :rate, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :人数 %>
    <%= f.number_field :ninnzuu, :size => 10 %>
  </div>


  <div class="field">
    <%= f.label :ポジション  %>
    <%= f.select :position, 
    [["BB", "BB"], 
    ["SB", "SB"], 
    ["BTN", "BTN"],
    ["CO", "CO"],
    ["HJ", "HJ"],
    ["MP2", "MP2"],
    ["MP1", "MP1"],
    ["UTG+1", "UTG+1"],
    ["UTG", "UTG"]], include_blank: "選択して下さい" %>
  </div>
 <div class="field">
    <%= f.label :ハンド入力（スートは書かないで！） %>
    <%= f.text_field :myhand, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :MYハンドスート入力欄1 %>
    <%= f.select :mark, 
    [["♠", "♠"], 
    ["♡", "♡"], 
    ["◇", "◇"],
    ["♣", "♣"]], include_blank: "選択して下さい" %>
    <%= f.label :MYハンドスート入力欄2 %>
    <%= f.select :mark, 
    [["♠", "♠"], 
    ["♡", "♡"], 
    ["◇", "◇"],
    ["♣", "♣"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :ハンドヒストリー記入欄（プリフロップ） %>
    <%= f.text_field :turn1, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action1, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action2, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action3, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
 <div class="field">
    <%= f.label :フロップ１枚目記入欄 %>
    <%= f.select :frop1, 
    [["A", "A"], 
    ["K", "K"], 
    ["Q", "Q"],
    ["J", "J"], 
    ["10", "10"],
    ["9", "9"], 
    ["8", "8"],
    ["7", "7"],
    ["6", "6"], 
    ["5", "5"],
    ["4", "4"],
    ["3", "3"], 
    ["2", "2"]], include_blank: "選択して下さい" %>
    <%= f.label :マーク記入欄 %>
    <%= f.select :frop1m,
    [["♠", "♠"], 
    ["♡", "♡"], 
    ["◇", "◇"],
    ["♣", "♣"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :フロップ２枚目記入欄 %>
    <%= f.select :frop2,
    [["A", "A"], 
    ["K", "K"], 
    ["Q", "Q"],
    ["J", "J"], 
    ["10", "10"],
    ["9", "9"], 
    ["8", "8"],
    ["7", "7"],
    ["6", "6"], 
    ["5", "5"],
    ["4", "4"],
    ["3", "3"], 
    ["2", "2"]], include_blank: "選択して下さい" %>
    <%= f.label :マーク記入欄 %>
    <%= f.select :frop2m,
    [["♠", "♠"], 
    ["♡", "♡"], 
    ["◇", "◇"],
    ["♣", "♣"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :フロップ３枚目記入欄 %>
    <%= f.select :frop3,
    [["A", "A"], 
    ["K", "K"], 
    ["Q", "Q"],
    ["J", "J"], 
    ["10", "10"],
    ["9", "9"], 
    ["8", "8"],
    ["7", "7"],
    ["6", "6"], 
    ["5", "5"],
    ["4", "4"],
    ["3", "3"], 
    ["2", "2"]], include_blank: "選択して下さい" %>
    <%= f.label :マーク記入欄 %>
    <%= f.select :frop3m,
    [["♠", "♠"], 
    ["♡", "♡"], 
    ["◇", "◇"],
    ["♣", "♣"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :ハンドヒストリー記入欄（フロップ） %>
    <%= f.text_field :turn2, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action4, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action5, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :ターンカード記入欄 %>
    <%= f.select :turn,
    [["A", "A"], 
    ["K", "K"], 
    ["Q", "Q"],
    ["J", "J"], 
    ["10", "10"],
    ["9", "9"], 
    ["8", "8"],
    ["7", "7"],
    ["6", "6"], 
    ["5", "5"],
    ["4", "4"],
    ["3", "3"], 
    ["2", "2"]], include_blank: "選択して下さい" %>
    <%= f.label :マーク記入欄 %>
    <%= f.select :turnm,
    [["♠", "♠"], 
    ["♡", "♡"], 
    ["◇", "◇"],
    ["♣", "♣"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :ハンドヒストリー記入欄（ターン） %>
    <%= f.text_field :turn3, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action6, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action7, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :リバーカード記入欄 %>
    <%= f.select :river,
    [["A", "A"], 
    ["K", "K"], 
    ["Q", "Q"],
    ["J", "J"], 
    ["10", "10"],
    ["9", "9"], 
    ["8", "8"],
    ["7", "7"],
    ["6", "6"], 
    ["5", "5"],
    ["4", "4"],
    ["3", "3"], 
    ["2", "2"]], include_blank: "選択して下さい" %>
    <%= f.label :マーク記入欄 %>
    <%= f.select :riverm,
    [["♠", "♠"], 
    ["♡", "♡"], 
    ["◇", "◇"],
    ["♣", "♣"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :ハンドヒストリー記入欄（リバー） %>
    <%= f.text_field :turn4, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action8, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action9, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :自分のアクション %>
    <%= f.select :action10, 
    [["チェック", "チェック"], 
    ["ベット", "ベット"], 
    ["コール", "コール"],
    ["フォールド", "フォールド"], 
    ["レイズ", "レイズ"]], include_blank: "選択して下さい" %>
  </div>
  <%= f.submit "編集する" %>
  
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/index.html.erb
<div class="tweets-container">
<%= link_to "ホーム", tweets_path %>


<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>

</div>





<div class="graph-wrapper">
  <%# All Action Rate %>
  <div class="flop-graph1">
    <div class="graph-title">All Action Rate</div>
    <%= pie_chart({
      "チェック" => @check_percent,
      "ベット" => @bet_percent,
      "コール" => @call_percent,
      "レイズ" => @raise_percent,
      "フォールド" => @fold_percent
    }, donut: true, library: { chart: { width: 300, height: 300 } },
       colors: ["#6b8e23", "#ffa500", "#2db386", "#f08080","#4682b4"]) %>
  </div>
  <div class="phase-graphs-container">
      <%# 左：Preflop Action Rate %>
      <div class="flop-graph2">
        <div class="graph-title">Prefrop Action Rate</div>
        <%= pie_chart({
          "チェック" => @check_percent1,
          "ベット" => @bet_percent1,
          "コール" => @call_percent1,
          "レイズ" => @raise_percent1,
          "フォールド" => @fold_percent1
        }, donut: true, library: { chart: { width: 300, height: 300 } },
          colors: ["#6b8e23", "#ffa500", "#2db386", "#f08080","#4682b4"]) %>
          </div>
        <%# 左：Frop Action Rate %>
      <div class="flop-graph3">
        <div class="graph-title">Flop Action Rate</div>
        <%= pie_chart({
          "チェック" => @check_percent2,
          "ベット" => @bet_percent2,
          "コール" => @call_percent2,
          "レイズ" => @raise_percent2,
          "フォールド" => @fold_percent2
        }, donut: true, library: { chart: { width: 300, height: 300 } },
          colors: ["#6b8e23", "#ffa500", "#2db386", "#f08080","#4682b4"]) %>
          </div>
        <%# 左：Turn Action Rate %>
      <div class="flop-graph4">
        <div class="graph-title">Turn Action Rate</div>
        <%= pie_chart({
          "チェック" => @check_percent3,
          "ベット" => @bet_percent3,
          "コール" => @call_percent3,
          "レイズ" => @raise_percent3,
          "フォールド" => @fold_percent3
        }, donut: true, library: { chart: { width: 300, height: 300 } },
          colors: ["#6b8e23", "#ffa500", "#2db386", "#f08080","#4682b4"]) %>
          </div>
      <%# 左：River Action Rate %>
      <div class="flop-graph5">
        <div class="graph-title">River Action Rate</div>
          <%= pie_chart({
            "チェック" => @check_percent4,
            "ベット" => @bet_percent4,
            "コール" => @call_percent4,
            "レイズ" => @raise_percent4,
            "フォールド" => @fold_percent4
          }, donut: true, library: { chart: { width: 300, height: 300 } },
            colors: ["#6b8e23", "#ffa500", "#2db386", "#f08080","#4682b4"]) %>
            </div>
  </div>

<div class="toukou"> 

<h4>投稿を検索</h4>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
 <h5>投稿一覧<h5>

  <% @tweets.each do |t| %>

<% if user_signed_in? && current_user.id == t.user_id %> 

    <%= link_to t.user.name, user_path(t.user.id) %>

    <div class="tweet">
      <%= t.shurui %>
      <%= t.rate %>
      人数:<%= t.ninnzuu %>
      ポジション:<%= t.position %>
      
      <div class="myhand">
        MY hand:<%= t.myhand %>
        <%= t.mark %>
        <%= t.suit %>
      </div>
      ボード
      <div class="card-container">
    <div class="card">
        <p class="label"><%= t.frop1 %></p>
        <p class="value"><%= t.frop1m %></p>
    </div>
    <div class="card">
        <p class="label"><%= t.frop2 %></p>
        <p class="value"><%= t.frop2m %></p>
    </div>
    <div class="card">
        <p class="label"><%= t.frop3 %></p>
        <p class="value"><%= t.frop3m %></p>
    </div>
    <div class="card">
        <p class="label"><%= t.turn %></p>
        <p class="value"><%= t.turnm %></p>
    </div>
    <div class="card">
        <p class="label"><%= t.river %></p>
        <p class="value"><%= t.riverm %></p>
    </div>
</div>
      <%= t.turn1 %>
      <%= t.turn2 %>
      <%= t.turn3 %>
      <%= t.turn4 %>
    </div>

    <%= link_to "編集する", edit_tweet_path(t.id) %>
    <%= button_to "削除する", tweet_path(t.id), method: :delete, data: { confirm: '本当に削除しますか？' } %>
  <% end %>


  <% end %>
  </div>
  </div>
<% end %>